spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://baza-date-zboruri:5432/db_zboruri}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:utilizator}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:parola123}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect